Sleep 3s
Type "btop"
Enter
Sleep 5.5s
Type "q"
Sleep 1.5s
Ctrl+C
Sleep 2s
Type "ls -lht"
Enter
Sleep 3.5s
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[A"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape

