"""initial schema

Revision ID: 0c196bca2dc0
Revises: 
Create Date: 2026-03-08 09:57:19.849814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c196bca2dc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('sport', sa.String(length=64), nullable=True),
    sa.Column('sub_sport', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time_s', sa.Integer(), nullable=True),
    sa.Column('moving_time_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr', sa.SmallInteger(), nullable=True),
    sa.Column('avg_cadence', sa.SmallInteger(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('descent_m', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('aerobic_effect', sa.Float(), nullable=True),
    sa.Column('anaerobic_effect', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activities_start_time'), 'activities', ['start_time'], unique=False)
    op.create_table('activity_derived',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('efficiency_factor', sa.Float(), nullable=True),
    sa.Column('pace_decoupling_pct', sa.Float(), nullable=True),
    sa.Column('cardiac_drift_pct', sa.Float(), nullable=True),
    sa.Column('hr_recovery_1min', sa.SmallInteger(), nullable=True),
    sa.Column('hr_recovery_2min', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_hr_zones',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('zone', sa.SmallInteger(), nullable=False),
    sa.Column('time_in_zone_s', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id', 'zone')
    )
    op.create_table('activity_laps',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('lap_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr', sa.SmallInteger(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id', 'lap_index')
    )
    op.create_table('activity_records',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('record_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('hr', sa.SmallInteger(), nullable=True),
    sa.Column('cadence', sa.SmallInteger(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id', 'record_index')
    )
    op.create_table('app_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('supporting_metrics', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_period_start'), 'assessments', ['period_start'], unique=False)
    op.create_table('blood_pressure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('systolic', sa.SmallInteger(), nullable=True),
    sa.Column('diastolic', sa.SmallInteger(), nullable=True),
    sa.Column('pulse', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_pressure_timestamp'), 'blood_pressure', ['timestamp'], unique=False)
    op.create_table('body_battery_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_battery_events_date'), 'body_battery_events', ['date'], unique=False)
    op.create_table('body_composition',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('hydration_pct', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Integer(), nullable=True),
    sa.Column('metabolic_age', sa.SmallInteger(), nullable=True),
    sa.Column('visceral_fat', sa.SmallInteger(), nullable=True),
    sa.Column('physique_rating', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('correlation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('metric_a', sa.String(length=64), nullable=False),
    sa.Column('metric_b', sa.String(length=64), nullable=False),
    sa.Column('lag_days', sa.SmallInteger(), nullable=False),
    sa.Column('r_pearson', sa.Float(), nullable=True),
    sa.Column('r_spearman', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_results_computed_at'), 'correlation_results', ['computed_at'], unique=False)
    op.create_table('daily_derived',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trimp', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('monotony', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('sleep_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('sleep_debt_min', sa.Float(), nullable=True),
    sa.Column('sleep_sri', sa.Float(), nullable=True),
    sa.Column('social_jet_lag_h', sa.Float(), nullable=True),
    sa.Column('lbm_kg', sa.Float(), nullable=True),
    sa.Column('ffmi', sa.Float(), nullable=True),
    sa.Column('body_recomp_index', sa.Float(), nullable=True),
    sa.Column('weight_velocity', sa.Float(), nullable=True),
    sa.Column('readiness_composite', sa.Float(), nullable=True),
    sa.Column('wellness_score', sa.Float(), nullable=True),
    sa.Column('overtraining_risk', sa.SmallInteger(), nullable=True),
    sa.Column('injury_risk', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('daily_summary',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('calories_total', sa.Integer(), nullable=True),
    sa.Column('calories_bmr', sa.Integer(), nullable=True),
    sa.Column('calories_active', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.SmallInteger(), nullable=True),
    sa.Column('hr_min', sa.SmallInteger(), nullable=True),
    sa.Column('hr_max', sa.SmallInteger(), nullable=True),
    sa.Column('hr_resting', sa.SmallInteger(), nullable=True),
    sa.Column('stress_avg', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_max', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_min', sa.SmallInteger(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('respiration_avg', sa.Float(), nullable=True),
    sa.Column('hydration_intake_ml', sa.Integer(), nullable=True),
    sa.Column('hydration_goal_ml', sa.Integer(), nullable=True),
    sa.Column('intensity_min_moderate', sa.Integer(), nullable=True),
    sa.Column('intensity_min_vigorous', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('data_provenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('flag_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_flags_date'), 'data_quality_flags', ['date'], unique=False)
    op.create_table('endurance_score',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('gear',
    sa.Column('gear_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('date_begin', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('gear_uuid')
    )
    op.create_table('gear_stats',
    sa.Column('gear_uuid', sa.String(length=64), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=True),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('gear_uuid')
    )
    op.create_table('goal_benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hill_score',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('hrv_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('hrv_5min_high', sa.Float(), nullable=True),
    sa.Column('hrv_5min_low', sa.Float(), nullable=True),
    sa.Column('baseline_low', sa.Float(), nullable=True),
    sa.Column('baseline_high', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('lactate_threshold',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lt_speed', sa.Float(), nullable=True),
    sa.Column('lt_hr', sa.SmallInteger(), nullable=True),
    sa.Column('lt_power', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('monitoring_climb',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('descent_m', sa.Float(), nullable=True),
    sa.Column('cum_ascent_m', sa.Float(), nullable=True),
    sa.Column('cum_descent_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('monitoring_heart_rate',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hr', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('monitoring_intensity',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('moderate_time_s', sa.Integer(), nullable=True),
    sa.Column('vigorous_time_s', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('monitoring_pulse_ox',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('monitoring_respiration',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('monitoring_steps',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_predictions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pred_5k_s', sa.Integer(), nullable=True),
    sa.Column('pred_10k_s', sa.Integer(), nullable=True),
    sa.Column('pred_half_s', sa.Integer(), nullable=True),
    sa.Column('pred_full_s', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('resting_heart_rate',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_hr', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('schema_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('total_sleep_min', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_min', sa.Integer(), nullable=True),
    sa.Column('light_sleep_min', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_min', sa.Integer(), nullable=True),
    sa.Column('awake_min', sa.Integer(), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('qualifier', sa.String(length=32), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.Column('avg_stress', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('sleep_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_events_date'), 'sleep_events', ['date'], unique=False)
    op.create_table('steps_activities',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('pace_avg', sa.Float(), nullable=True),
    sa.Column('pace_moving', sa.Float(), nullable=True),
    sa.Column('pace_max', sa.Float(), nullable=True),
    sa.Column('steps_per_min', sa.Float(), nullable=True),
    sa.Column('step_length_m', sa.Float(), nullable=True),
    sa.Column('vertical_oscillation_mm', sa.Float(), nullable=True),
    sa.Column('vertical_ratio_pct', sa.Float(), nullable=True),
    sa.Column('gct_ms', sa.Float(), nullable=True),
    sa.Column('stance_pct', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('stress',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stress_level', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('records_upserted', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_started_at'), 'sync_log', ['started_at'], unique=False)
    op.create_table('sync_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_readiness',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('recovery_score', sa.SmallInteger(), nullable=True),
    sa.Column('training_load_score', sa.SmallInteger(), nullable=True),
    sa.Column('hrv_score', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('training_status',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('load_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('trend_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('lookback_days', sa.SmallInteger(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_classifications_date'), 'trend_classifications', ['date'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vo2max',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vo2max_running', sa.Float(), nullable=True),
    sa.Column('vo2max_cycling', sa.Float(), nullable=True),
    sa.Column('fitness_age', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('weekly_derived',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('atl_avg', sa.Float(), nullable=True),
    sa.Column('ctl_avg', sa.Float(), nullable=True),
    sa.Column('tsb_avg', sa.Float(), nullable=True),
    sa.Column('weekly_load', sa.Float(), nullable=True),
    sa.Column('polarized_z1_pct', sa.Float(), nullable=True),
    sa.Column('polarized_z2_pct', sa.Float(), nullable=True),
    sa.Column('polarized_z3_pct', sa.Float(), nullable=True),
    sa.Column('intensity_min_mod', sa.Integer(), nullable=True),
    sa.Column('intensity_min_vig', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('week_start')
    )
    op.create_table('weight',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight')
    op.drop_table('weekly_derived')
    op.drop_table('vo2max')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_trend_classifications_date'), table_name='trend_classifications')
    op.drop_table('trend_classifications')
    op.drop_table('training_status')
    op.drop_table('training_readiness')
    op.drop_table('sync_schedule')
    op.drop_index(op.f('ix_sync_log_started_at'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_table('stress')
    op.drop_table('steps_activities')
    op.drop_index(op.f('ix_sleep_events_date'), table_name='sleep_events')
    op.drop_table('sleep_events')
    op.drop_table('sleep')
    op.drop_table('schema_version')
    op.drop_table('resting_heart_rate')
    op.drop_table('race_predictions')
    op.drop_table('personal_records')
    op.drop_table('notification_config')
    op.drop_table('monitoring_steps')
    op.drop_table('monitoring_respiration')
    op.drop_table('monitoring_pulse_ox')
    op.drop_table('monitoring_intensity')
    op.drop_table('monitoring_heart_rate')
    op.drop_table('monitoring_climb')
    op.drop_table('lactate_threshold')
    op.drop_table('hrv_data')
    op.drop_table('hill_score')
    op.drop_table('goals')
    op.drop_table('goal_benchmarks')
    op.drop_table('gear_stats')
    op.drop_table('gear')
    op.drop_table('endurance_score')
    op.drop_index(op.f('ix_data_quality_flags_date'), table_name='data_quality_flags')
    op.drop_table('data_quality_flags')
    op.drop_table('data_provenance')
    op.drop_table('daily_summary')
    op.drop_table('daily_derived')
    op.drop_index(op.f('ix_correlation_results_computed_at'), table_name='correlation_results')
    op.drop_table('correlation_results')
    op.drop_table('body_composition')
    op.drop_index(op.f('ix_body_battery_events_date'), table_name='body_battery_events')
    op.drop_table('body_battery_events')
    op.drop_index(op.f('ix_blood_pressure_timestamp'), table_name='blood_pressure')
    op.drop_table('blood_pressure')
    op.drop_index(op.f('ix_assessments_period_start'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('app_config')
    op.drop_table('activity_records')
    op.drop_table('activity_laps')
    op.drop_table('activity_hr_zones')
    op.drop_table('activity_derived')
    op.drop_index(op.f('ix_activities_start_time'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
